### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by DeadlyMagikarps**
Removing solution file. Unity generates one uniquely per user based on what they name their project. This was likely pushed before the gitignore was submitted.

File Naming Conventions updated and files moved to those new folders.

Nothing functionally has changed. Just a cleanup for a cleaner master branch based on URP.

### CODE REVIEW

**Comment by olawlor** [comment]
Do the airlocks still work for you after this?  The GUID on Assets/Architecture/Temporary_Buildings/Modular_6m/Modular_6m_Airlock.cs.meta seems to have been changed by this commit, breaking them for me.

**Comment by DeadlyMagikarps** [comment]
That doesn't actually exist on my HDRP branch. Which might be why it got deleted. 
Does it work on your master branch still?

**Comment by olawlor** [comment]
I got airlocks working again and pushed.  Somehow changing the script's .cs.meta file GUID screwed up all the uses of the script in prefabs.

I'll be more careful about watching changes to .meta files in the future.

**Comment by DeadlyMagikarps** [comment]
Gotcha. Ya. meta data is important... We'll eventually get this smooth. It's looking a lot cleaner than at first now. Especially with the gitignore, and close to perfect sync with the branches. Master is a copy of your Master which runs on URP. Is that correct? Mine is HDRP -> HDRP while my forked master is this master which is URP.

Whew, what a mouthful.

**Pull request merged**
