### PR TITLE
Update ReadMe

### PR DESCRIPTION
**Pull request by DeadlyMagikarps**

### CODE REVIEW

**Comment by olawlor** [comment]
If you load :develop in Unity 2019.4, you get a ton of "Failed to load" errors because "File may be corrupted or was serialized with a newer version of Unity".

So the README shouldn't get updated until we have one scene that actually works in 2019.4.

**Comment by DeadlyMagikarps** [comment]
Yes. This project is getting downgraded to the below. I haven't sent that PR yet.

**Comment by olawlor** [comment]
It doesn't make sense to update the README if the project doesn't work there yet though.  I notice :master imports into 2019.4 fine (although there's not much there aside from my terrain).

**Comment by olawlor** [comment]
The "Click Here" button at the bottom of the README needs updating to na-unity-virtual-colony-experimental too.

**Comment by DeadlyMagikarps** [comment]
> The "Click Here" button at the bottom of the README needs updating to na-unity-virtual-colony-experimental too.

Where are you seeing "Click Here" button?

**Comment by DeadlyMagikarps** [comment]
> It doesn't make sense to update the README if the project doesn't work there yet though. I notice :master imports into 2019.4 fine (although there's not much there aside from my terrain).

It's been redone. It couldn't upload because of the assets being too big.

**Comment by olawlor** [comment]
:master here is actually 2018, and it imports OK into 2019.4

**Comment by olawlor** [comment]
> > The "Click Here" button at the bottom of the README needs updating to na-unity-virtual-colony-experimental too.
> 
> Where are you seeing "Click Here" button?

It's under "How to start".

**Comment by DeadlyMagikarps** [comment]
Gotcha. Ya. so we need to sync everything to the correct version 2019.4.0f LTS.

Ah, I see it now. So there is information on there that is out of date. I think it might be better to omit all that for now until we have a tech lead. I will correct the readme to address the changes. I'm working on the actual PR so this readme will make sense.

**Pull request closed without merging**
